# Site settings
title: "Conference coffee"
tagline: "The best conference coffee and tea"

# Handling Reading
safe: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
permalink: /:categories/:title/
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from

# Contact
email: ""

# Social
#facebook: egsr-4668468684?
#twitter: egsr


# Use this for production
sass:
    style: compressed
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]


theme: jekyll-theme-slate